config/routes.rb
Rails.application.routes.draw do
  resources :currencies, only: :index
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "currencies#history"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many :currency_data
end

app/models/currency_history.rb
class CurrencyHistory < ApplicationRecord
  belongs_to :currency

  def self.save_todays_data
    Currency.all.pluck(:cbr_id).each do |cbr_id|
      raw_data = CbrClient.new.daily(Date.current)
      prepared_data = CurrencyParser.new(raw_data).daily_by_id(cbr_id)

      CurrencyHistory.create!(prepared_data)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController

  def index
    @currencies = Currency.all.map do |cur|
      {cur => CurrencyHistory.where(date: 1.month.ago..Date.today, currency: cur)}
    end
  end

  def history
    @currencies = Currency.all.map do |cur|
      {
        cur.char_code => {
          last_week_1: [
            CurrencyHistory.where(date: (Date.today.beginning_of_week.weeks_ago(1) + 1).., currency: cur).limit(1),
            CurrencyHistory.where(date: (Date.today.end_of_week.weeks_ago(1) - 1).., currency: cur).limit(1)
          ],
          last_week_2: [
            CurrencyHistory.where(date: (Date.today.beginning_of_week.weeks_ago(2) + 1).., currency: cur).limit(1),
            CurrencyHistory.where(date: (Date.today.end_of_week.weeks_ago(2) - 1).., currency: cur).limit(1)
          ],
          last_week_3: [
            CurrencyHistory.where(date: (Date.today.beginning_of_week.weeks_ago(3) + 1).., currency: cur).limit(1),
            CurrencyHistory.where(date: (Date.today.end_of_week.weeks_ago(3) - 1).., currency: cur).limit(1)
          ],
          last_week_4: [
            CurrencyHistory.where(date: (Date.today.beginning_of_week.weeks_ago(4) + 1).., currency: cur).limit(1),
            CurrencyHistory.where(date: (Date.today.end_of_week.weeks_ago(4) - 1).., currency: cur).limit(1)
          ]
        }
      }
    end

    calculate_change
  end

  private

  def calculate_change
    @currencies.map do |cur|
      cur.values.map do |weeks|
        weeks.each do |key, value|
          if value[1] && value[0]
            persent = (((value[1].first.rate - value[0].first.rate) / value[1].first&.rate) * 100).round(2)
            persent_str = persent.positive? ? '+' + persent.to_s : persent.to_s
            last_value = value[1].first.rate.round(2)

            weeks[key] = [persent_str, last_value]
          end
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_currency.html.erb
<% name = currency.keys.first.char_code %>
<h1><%= currency.keys.first.name %></h1>
<div id="<%= name %>">
  <div id="<%= name %>"></div>
  <script>
    var chart = c3.generate({
      bindto: "<%= "##{name}" %>",
      data: {
        columns: [
          <%= currency.values.first.map {|h| h[:rate]}.unshift(currency.keys.first.char_code).to_json.html_safe %>
        ]
      }
    });
  </script>

</div>

app/views/currencies/_row.html.erb
<tr>
  <td><%= currency.keys.first %></td>
  <td><%= "#{currency.values.first[:last_week_4][1]}  (#{currency.values.first[:last_week_4][0]})" %></td>
  <td><%= "#{currency.values.first[:last_week_3][1]}  (#{currency.values.first[:last_week_3][0]})" %></td>
  <td><%= "#{currency.values.first[:last_week_2][1]}  (#{currency.values.first[:last_week_2][0]})" %></td>
  <td><%= "#{currency.values.first[:last_week_1][1]}  (#{currency.values.first[:last_week_1][0]})" %></td>
</tr>

app/views/currencies/history.html.erb
<table>
  <tr>
    <th>Валюта</th>
    <th>4 недели назад</th>
    <th>3 недели назад</th>
    <th>позапрошлая неделя</th>
    <th>прошлая неделя</th>
  </tr>

  <% @currencies.each do |currency| %>
    <%= render partial: "row", locals: {currency: currency} %>
  <% end %>
</table>

app/views/currencies/index.html.erb
<div id="currencies">
  <% @currencies.each do |currency| %>
    <%= render partial: "currency", locals: {currency: currency} %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrencyInfo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.js"></script>
  </head>

  <body>
    <%= link_to "Graphs", currencies_path %>
    <%= link_to "Table", root_path %>

    <%= yield %>
  </body>
</html>